### ISSUE TITLE
Create config file for CI tests with python 3.9 and 3.10

### ISSUE THREAD

**Issue by BenjMy** [Peruz/icsd#13]
Up to now, the coverage test using the [CI workflow](https://github.com/Peruz/icsd/blob/main/.github/workflows/tests_package.yml) is **only done for python 3.8 with os ubuntu**.  We need to **extend it to 3.9 and 3.10 and to macos and windows os**.

Adding the following two files in the test folder: 
- tests/envs/39-env.yaml
```
name: test
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ...
```

- tests/envs/310-env.yaml
```
name: test
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ...
```
And the following strategy command in the [CI workflow](https://github.com/Peruz/icsd/blob/main/.github/workflows/tests_package.yml)

```
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            env: tests/envs/38-env.yaml
            py: py3.8

          - os: ubuntu-latest
            env: tests/envs/39-env.yaml
            py: py3.9

          - os: ubuntu-latest
            env: tests/envs/310-env.yaml
            py: py3.10

          - os: macos-latest
            env: tests/envs/310-env.yaml
            py: py3.10

          - os: windows-latest
            env: tests/envs/310-env.yaml
            py: py3.10

```
